# This is a basic workflow to help you get started with Actions

name: CI
defaults:
  run:
    shell: bash
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  windows:
    name: Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [win32, x64, arm64]
    env:
      PLATFORM: ${{ matrix.platform }}
      OPENRCT2_VERSION:       0.4.15
      OPENRCT2_VERSION_EXTRA: 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build artifacts
        run: |
          scripts/build-installer -i
      - name: Upload artifacts (CI)
        uses: actions/upload-artifact@v4
        with:
          name: OpenRCT2-${{ env.OPENRCT2_VERSION }}-${{ runner.os }}-${{ matrix.platform }}
          path: artifacts
          if-no-files-found: error
